### ISSUE TITLE
Nexus5 boot.img too large

### ISSUE THREAD

**Issue by chr1shaefn3r** [silklabs/silk#22]
After @mvines fixed the build issues (thanks again for that), I'm now stuck with another error trying to flash the boot.img

```
$ fastboot flash boot boot.img
target reported max download size of 1073741824 bytes
sending 'boot' (28899 KB)...
OKAY [  1.017s]
writing 'boot'...
FAILED (remote: size too large)
finished. total time: 1.197s
```

I'm taking it out of the out/target/product/msm8952_64/ folder. Not sure if thats the right one, though.

Can someone confirm that the [Docker build description](https://github.com/silklabs/silk/tree/master/docker) worked for him, and he was successfully able to flash the images (boot, system, recovery, splash)?

**Comment by mvines** [comment]
My N5 device is MIA so unfortunately I can't confirm/deny a problem with the N5 build at the moment.   We regularly use the Kenzo and N4 builds though, so I'm pretty confident those are solid FWIW

**Comment by mvines** [comment]
I just build/loaded N5 with: 
```sh
$ cd bsp-gonk/
$ ./sync hammerhead
$ . build/envsetup.sh
$ make -j$(nproc)
$ fastboot flashall
```
and everything looks fine.

The boot.img should be `out/target/product/hammerhead/boot.img` though, not `out/target/product/msm8952_64/boot.img`.  It sounds like maybe you tried to load a kenzo boot.img on a N5 device?

Please re-open if there's anything new to report here.  Otherwise I don't think there's anything to do.  Thanks!
